# See: https://github.com/DavidAnson/markdownlint

# Unordered list style
MD004:
  style: dash

MD013:
  line_length: 99
  heading_line_length: 99
  code_block_line_length: 99
  # Disable line length for tables
  tables: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
