# See: https://prettier.io/docs/en/configuration

printWidth: 80
tabWidth: 2
useTabs: false
quoteProps: as-needed
trailingComma: es5
bracketSpacing: true
arrowParens: always
proseWrap: always
htmlWhitespaceSensitivity: css
endOfLine: lf
